# Generated by Django 3.1.14 on 2022-12-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20221227_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Иконка')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Название по-русски')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название по-английски')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название по-японски')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
