# Generated by Django 3.1.14 on 2022-12-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemonelements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonElements',
            new_name='PokemonElement',
        ),
    ]
