# Generated by Django 3.1.14 on 2022-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20221228_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelement',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemonelement',
            name='pokemon',
            field=models.ManyToManyField(null=True, related_name='elements', to='pokemon_entities.Pokemon', verbose_name='Покемон'),
        ),
    ]
