# Generated by Django 3.1.14 on 2022-12-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20221228_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelement',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='elements',
            field=models.ManyToManyField(null=True, related_name='elements', to='pokemon_entities.PokemonElement', verbose_name='Стихии'),
        ),
    ]
