# Generated by Django 3.1.14 on 2022-12-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20221228_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonelement',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='pokemonelement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pokemonelement',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pokemonelement',
            name='title_jp',
        ),
    ]
