# Generated by Django 3.1.14 on 2022-12-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20221228_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelement',
            name='strong_against_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pokemonelement_strong_against_type_+', to='pokemon_entities.PokemonElement', verbose_name='Силён против'),
        ),
    ]
